<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_module' => [[], ['_controller' => 'App\\Controller\\API\\ModuleController::index'], [], [['text', '/api/modules']], [], [], []],
    'api_me' => [[], ['_controller' => 'App\\Controller\\API\\UserController::me'], [], [['text', '/api/me']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
    'App\Controller\API\ModuleController::index' => [[], ['_controller' => 'App\\Controller\\API\\ModuleController::index'], [], [['text', '/api/modules']], [], [], []],
    'App\Controller\API\UserController::me' => [[], ['_controller' => 'App\\Controller\\API\\UserController::me'], [], [['text', '/api/me']], [], [], []],
];
